server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/data?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: WoW161726
mybatis-plus:
  typeAliasesPackage: com.common.ctdenoising.entity
  mapperLocations: classpath:mapper/*.xml
file:
  save-path: \RED-CNN-master(Lite)\data
logging:
  level:
    root: INFO
    web: DEBUG
